### ISSUE TITLE
Hangs in shrinking / testcase failure

### ISSUE THREAD

**Issue by bluss** [BurntSushi/quickcheck#107]
Current git version seems to hang after a test failure, continuously spawning new threads.

**Comment by bluss** [comment]
This is enough for me to reproduce a hang:

```
#[test]
fn qc_bug() {
    fn prop(a: Vec<u8>) -> bool {
        a.contains(&1)
    }
    quickcheck::quickcheck(prop as fn(_) -> bool);
}
```

**Comment by bluss** [comment]
The bug is not in 49db7a7

cc @SeanRBurton due to recently merged PRs, maybe you know what's going on?

**Comment by BurntSushi** [comment]
Yeah, I haven't had time to grok those PRs yet (which is why I haven't published a new release). If I can't find time today or tomorrow, I'll revert and revisit them later.
