### ISSUE TITLE
Add Arbitrary implementation for `std::time` (optionally)

### ISSUE THREAD

**Issue by sgrif** [BurntSushi/quickcheck#109]
Would be great to be able to generate these arbitrarily with `features = ["unstable"]`. It seems like this should probably `impl Arbitrary` for every reasonable owned type in the std library.

**Comment by BurntSushi** [comment]
"every reasonable owned type" sounds like a pretty good heuristic to me!

**Comment by sgrif** [comment]
I'll go ahead and submit a PR for this one if you're interested.

**Comment by BurntSushi** [comment]
@sgrif That would be lovely! Thank you. :-)
