### ISSUE TITLE
Seed and print the value of seed used on failure

### ISSUE THREAD

**Issue by Wilfred** [BurntSushi/quickcheck#121]
I have tests that fail very rarely. When this happens on Travis, I'd really like to reproduce the issue locally.

If quickcheck randomly chose a seed, but printed that seed value on failure, then I could replicate test failures.

**Comment by BurntSushi** [comment]
Hmm. The failures should print the arguments with which the test ran. That should be sufficient to reproduce the failure?

**Comment by Wilfred** [comment]
You're right, that's totally sufficient. Sorry for the noise.

**Comment by PureW** [comment]
For more complex test-input, it is not always that simple to refer to the debug output. It would be very useful if quickcheck could present reproducability steps on a failing test-case.

In the best of all worlds, giving a single one-liner that runs just the failing test-case with the failing test-input would be awesome.
