### ISSUE TITLE
Shall BLoNS be taked into account be String generator?

### ISSUE THREAD

**Issue by vi** [BurntSushi/quickcheck#122]
Shall [this](https://github.com/minimaxir/big-list-of-naughty-strings) be incorporated?

**Comment by BurntSushi** [comment]
Hmm, I'm not sure I'd want to pull this in. It seems less about "randomly generate some input and then shrink it" and more "here's some strings that tend to be problematic, do they work?"

With that said, if someone wanted to use it with quickcheck, it does feel like it could be prototyped in a separate crate as a distinct type. It is a neat idea.
