### ISSUE TITLE
Implement something like statem

### ISSUE THREAD

**Issue by nox** [BurntSushi/quickcheck#134]
See "State Machine Testing" in http://www.quviq.com/products/erlang-quickcheck/ and PropEr's https://github.com/manopapad/proper/blob/master/src/proper_statem.erl.

**Comment by BurntSushi** [comment]
I'm not sure when I'll have time to digest those links (the first at least seems a bit slim), but can it be prototyped in a separate crate first?

**Comment by nox** [comment]
I'm looking into that but very slowly.

Here is a better description btw: http://proper.softlab.ntua.gr/Tutorials/PropEr_testing_of_finite_state_machines.html

**Comment by nox** [comment]
Also: http://hypothesis.works/articles/rule-based-stateful-testing/

**Comment by JayKickliter** [comment]
I've used a Erlang Quickcheck at work for testing c code. `statem` is amazing at discovering bugs which require a long series of operations to provoke. I'd love similar functionality for Rust.

**Comment by JayKickliter** [comment]
Another [link](http://htmlpreview.github.io/?https://raw.github.com/strangeloop/lambdajam2013/master/slides/Norton-QuickCheck.html#1.0) with a real-world use case. TLDR: bug in google's `leveldb` which took 17ish operations to uncover.

**Comment by Horusiath** [comment]
Hi, I wanted to ask if there's any conclusion on that? I'm in high need of stateful property-based tests in my work. If there's nobody working on this issue, I could try to help and contribute. My only problem is that both my Rust skills and my model-testing knowledge are pretty rough atm and may require someone to supervise.

**Comment by BurntSushi** [comment]
I wish you luck. Unfortunately, I don't really have the bandwidth to contemplate models of property based testing that are different from how quickcheck currently works.
