### ISSUE TITLE
impl Shrink for structs

### ISSUE THREAD

**Issue by cramertj** [BurntSushi/quickcheck#135]
What's the current recommended practice for implementing shrink for structs? I've been implementing them as a series of `flat_map` calls on the shrink of the struct's members, but this is time consuming and irksome, producing rightward drift and requiring lots of copying in order to meet the lifetime requirements of the nested closures. Is this even something users should be doing? It seems that the resulting shrink would multiply in size with each member shrink performed, perhaps making the shrink prohibitive after a certain point. Is there some way to simultaneously shrink multiple members per iteration, perhaps pausing on test passes and checking each to find the member that shrank "too much"?

**Comment by BurntSushi** [comment]
One method might be to convert your struct to a tuple, shrink the tuple and then map it back to your struct. It feels like one could probably write a macro for this if you're writing it out a lot.

**Comment by cramertj** [comment]
I'm currently doing this a lot-- I'd be happy to contribute a macro for this if you can give me tips for where to start.

**Comment by BurntSushi** [comment]
@cramertj I'm actually not sure I'd want the macro included in this crate. However, I'm happy to help you implement one. Here's what I'm thinking: https://is.gd/sSynY2

I'm not really a macro hacker though, so maybe you can do better, but that seems reasonably good enough to me. If you're really curious, you might investigate @DanielKeep's [`custom_derive`](https://github.com/DanielKeep/rust-custom-derive) crate.

**Comment by cramertj** [comment]
Oh, okay. Is there some reason you don't want it included? It seems like a pretty common usecase.

**Comment by BurntSushi** [comment]
@cramertj I personally have a *very* high bar to exposing a macro in a public API. Avoiding a teeny bit of boiler plate in some cases doesn't really do it for me. You could define the macro in an external crate. :-)

**Comment by bluss** [comment]
the [rand_derive](https://crates.io/crates/rand_derive) strategy could work fine to implement a deriving macro for the Arbitrary trait, complete with shrinking. It's stable rust compatible and very powerful, Unfortunately it has some severe ergonomic limitations.
