### ISSUE TITLE
Improve readme on Gen combination and composition

### ISSUE THREAD

**Issue by jockbert** [BurntSushi/quickcheck#159]
Basically, I'm new to both QuickCheck and Rust. In ScalaCheck, I'm used to do generator combination and generator composition with ease. It might be trivial to do the same in Rust and QuickCheck, but I just don't know how. I think some examples in the QuickCheck Readme would help both me and QuickCheck.

**Generator Composition** 
How do I create a generator of _time_ from a generator of _hours_ and a generator _seconds_? How do I create a generator of _cars_ from a generator of _wheels_ and a Generator of _engines_?

**Generator Combination**
How do I combine a generator of squares and a generator of circles to get a generator of shapes?

Another example of combination, let say that the StdGen is insufficient for type f64. I want to combine a Generator (A) that gives values in the range [MIN, MAX] with another generator (B) that choose from the set of specific values _{INFINITY, NAN, NEGATIVE_INFINITY, ZERO}_. I might also want to specify the distribution, so that 90% of values should come from generator A and the last 10% of values from generator B. How do I do that?

**Comment by BurntSushi** [comment]
I'd probably look at the existing impls of `Arbitrary` for inspiration on this, since there is a lot of reuse. Otherwise, I kind of feel like this is more in the domain of `rand`?
