### ISSUE TITLE
Custom shrinker library?

### ISSUE THREAD

**Issue by sunshowers** [BurntSushi/quickcheck#170]
Thinking aloud a bit here.

So I'm trying to implement `Arbitrary` for a data structure where not all possible inner values are valid. (Classic problem with writing shrinkers for randomized test cases.) In my case the structure contains a `Vec` of inner values.

Now for my data structure, dropping arbitrary values from the `Vec` maintains the invariant, but reordering values doesn't. I presume there are lots of similar data structures in the wild. It does mean that I can't just use the standard `Vec::shrink`.

Would it make sense to provide a library with custom `shrink` implementations for different strategies, like "drop but don't reorder"?

**Comment by BurntSushi** [comment]
I'm very open to the idea of building better abstractions for shrinkers. I don't quite have the bandwidth to work on that problem myself---I usually just fix problems as they appear---but if it can be done in another crate, that sounds great.
