### ISSUE TITLE
Shrinking panicked runs?

### ISSUE THREAD

**Issue by sid0** [BurntSushi/quickcheck#171]
Often for longer test cases I'll tend to use the `assert_eq!` or `assert!` macros. It's also possible that some quickcheck-generated test cases find bugs that cause internal invariants to be violated.

Looks like quickcheck currently panics correctly but doesn't do any shrinking. I think shrinking would be pretty useful here.

**Comment by BurntSushi** [comment]
It should. Can you please provide a small demonstration of the bug?

**Comment by sid0** [comment]
OK, didn't know it was supposed to work :) I'll try coming up with a repro later today. Thanks.

**Comment by sid0** [comment]
OK, so I did some further digging in and it looks like I was just a bit confused. It looks like for panicked runs, during shrinking the test panicking is visible on stdout (or stderr, not sure which) during each run. (I'm running a test binary directly -- the behavior might be slightly different with `cargo test`.) That's what was confusing me. Otherwise shrinking does appear to work.

**Comment by BurntSushi** [comment]
@sid0 Right, that's the default panic handler running.
