### ISSUE TITLE
Outdated README?

### ISSUE THREAD

**Issue by michaelmior** [BurntSushi/quickcheck#178]
The README currently has the following statement:

> As of now, only functions with 4 or fewer parameters can be quickchecked.

Without testing, it seems like functions with 8 or fewer parameters are now usable.

**Comment by NobbZ** [comment]
Also the version(s) given in the [READMEs installing section](https://github.com/BurntSushi/quickcheck#installation) seem to be old.

I wasn't able to install them until I've seen at crates.io that there is actually 0.4.x available of both, quickcheck and quickcheck_macros.

**Comment by MortenLohne** [comment]
Also from the readme:

> Note that the #[quickcheck] macro will not work when Rust 1.0 stable is released

When looking for a maintained library, that's not very reassuring.
