### ISSUE TITLE
Consider making a new release

### ISSUE THREAD

**Issue by malbarbo** [BurntSushi/quickcheck#188]
The last release was in dezember/2016 (0.4.1). Consider making a new release so we can get the various improvements since then. Specifically, the updated env_logger so the downstream crates does not need to build two versions (0.3 for quickcheck and 0.4 for others crates).

**Comment by robinst** [comment]
+1. `env_logger` 0.3 also pulls in `regex` 0.1, so crates using both `quickcheck` and `regex` will end up building two different regex versions.

**Comment by bluss** [comment]
logging is a feature you can disable, so you don't have to compile it at all, if you don't need it.

**Comment by malbarbo** [comment]
@bluss I hadn't seen than logging is a feature! Thanks!

**Comment by BurntSushi** [comment]
Done. `quickcheck 0.5.0` is out!

**Comment by malbarbo** [comment]
Thanks!
