### ISSUE TITLE
Using a Gen besides StdGen<ThreadRng>

### ISSUE THREAD

**Issue by CrockAgile** [BurntSushi/quickcheck#189]
`StdGen` can use any implementer of `Rng`, such as `StdGen<IsaacRng>`, `StdGen<OsRng>`, `StdGen<XorShiftRng>`, etc. However the main `QuickCheck` type for configuring and running tests only implements `new()` for `StdGen<ThreadRng>`. Is this an oversight in its generics? Or is there a way to configure and run tests using these other randomness sources?

**Comment by Ryan1729** [comment]
You can use the [`gen` method](https://docs.rs/quickcheck/0.4.2/quickcheck/struct.QuickCheck.html#method.gen) after calling `new` to use another `StdGen` implementation. But that still involves creating a `ThreadRng` instance which, over a sufficiently large number of test runs, may not be desirable. I think having another initialization method (`new_with_gen`?) that allowed passing in another `StdGen` implementation seems like a good idea. In particular using seeded RNGs seems like it could have a wide array of uses.

**Comment by BurntSushi** [comment]
@Ryan1729 is right, use the `gen` method if you want to use a different generator.

I don't understand what a hypothetical `new_with_gen` would buy you that the existing `gen` mutator doesn't.

**Comment by Ryan1729** [comment]
I just had a look at the [`ThreadRng` docs](https://doc.rust-lang.org/rand/rand/fn.thread_rng.html) which say that the rng is lazily-initialized. In that case, then I agree a `new_with_gen` method wouldn't buy anyone very much.

**Comment by BurntSushi** [comment]
All righty, closing this. If anyone has any other thoughts please feel free to comment and we can revisit.
