### ISSUE TITLE
Selecting values for usize

### ISSUE THREAD

**Issue by russel** [BurntSushi/quickcheck#190]
I have a test with signature:
```rust
fn a_test(n: usize) -> bool
```
but all the selected values of n are in (0, 100) which seems counter-intuitive. Is this what I should expect?

**Comment by BurntSushi** [comment]
It is what the current implementation defaults to, yes. It is not ideal. A better generation strategy is welcome.

You can however change the range at which `usize` numbers are generated by [creating a `StdGen` with a custom size](https://docs.rs/quickcheck/0.5.0/quickcheck/struct.StdGen.html#method.new) and setting it on [`QuickCheck`](https://docs.rs/quickcheck/0.5.0/quickcheck/struct.QuickCheck.html#method.gen).

**Comment by DurhamG** [comment]
@BurntSushi If we have to create a QuickCheck object and set a new generator on it, does this mean we won't be able to use the quickcheck! macro?

I have to admit, it's pretty absurd that a fuzz testing library only checks numbers <100.  We had a bug in some serialization/deserialization code of u64's and it was never invoked because it never received a number that required more than one byte to serialize.

**Comment by BurntSushi** [comment]
> If we have to create a QuickCheck object and set a new generator on it, does this mean we won't be able to use the quickcheck! macro?

Yes.

> it's pretty absurd

You might reconsider your approach. This is unconstructive complaining that I absolutely refuse to deal with.

**Comment by DurhamG** [comment]
You're right, it wasn't helpful.  Sorry, I was just frustrated.

I see someone proposed a different distribution [here](https://github.com/BurntSushi/quickcheck/issues/119#issuecomment-277247881).  Any thoughts on that style of solution? I can look into making a pull request if that approach sounds reasonable.

**Comment by BurntSushi** [comment]
@DurhamG Ah yeah! That actually sounds like a great approach. We do the same thing for strings IIRC, so doing it for numbers makes a lot of sense. That's probably why I picked such a small range initially, to cover special cases that are typically small numbers (e.g., `0` and `1`). But moving that to a more sophisticated distribution that includes the full space of integers sounds great to me.

**Comment by plul** [comment]
Do you have an update on this? #221 was closed without merging, but I cannot see why.

**Comment by BurntSushi** [comment]
I didn't close it. Someone is welcome to resubmit it.
