### ISSUE TITLE
Set up QuickCheck::tests in-code

### ISSUE THREAD

**Issue by felix91gr** [BurntSushi/quickcheck#207]
Hi everyone!

First of all, thanks to the contributors for making QuickCheck. I really appreciate it :bowing_man:. Property-based testing is what got me into testing, and it's great to see it in Rust.

Second, here's my question: I have a binary crate (non-library), and I'd like to use the `main` for things other than testing. But the examples I've seen of setting `QuickCheck::tests` in-code do so inside the `main`. Can I do it somewhere else? Maybe inside the `tests` module?

And if it cannot be done... could I make `cargo test` trigger `QUICKCHECK_TESTS=1000` before running somehow?

I really appreciate the help. Links for further reading are welcome! I'm just getting started with Rust and the more I read, the more I like it ^^

**Comment by BurntSushi** [comment]
Have you looked at [the first example in the README](https://github.com/BurntSushi/quickcheck#simple-example)? It doesn't use `main` at all and fits right into Rust's built in unit testing facilities.

You can call quickcheck from anywhere. By default, it panics on test failures, which is typically how you indicate test failures in Rust.

I don't really understand your question about `QUICKCHECK_TESTS`. Could you please [read this section](https://github.com/BurntSushi/quickcheck/blob/8d3afe355aff9f88de9236ddc0a5ac21fd630993/README.md#discarding-test-results-or-properties-are-polymorphic), particularly the last paragraph, and perhaps rephrase your question?

**Comment by BurntSushi** [comment]
> However, if I could, I'd love to just run cargo test and those variables be sat in some configuration file somewhere. My second question is whether or not I can do that

There are a cornucopia of options available to you, because env vars can be injected in so many ways, and env vars are not the only thing that can set this. For example, as the README calls out, you can actually set this [in the code](https://docs.rs/quickcheck/0.6.2/quickcheck/struct.QuickCheck.html#method.tests) when you invoke QuickCheck.

With respect to env vars, you could:

* Create your own configuration file and `source` it before running `cargo test`.
* Write a wrapper script that sets the env vars and then invokes whatever other additional commands are given.

The world is your oyster.

**Comment by felix91gr** [comment]
> For example, as the README calls out, you can actually set this in the code when you invoke QuickCheck.

Can I do that outside of my `main`, though? The example in the README uses the `main` to set it up, and I'd prefer to leave the `main` without testing code.

> With respect to env vars, you could:
>
> - Create your own configuration file and source it before running cargo test.
> - Write a wrapper script that sets the env vars and then invokes whatever other additional commands are given.
>
> The world is your oyster.

Thanks for the heads up, I think I'll do exactly that if I can't do it in code :)

**Comment by BurntSushi** [comment]
@felix91gr The examples are just using `main` because they're examples. You can put that code anywhere. It's just code. e.g.,

```rust
#[test]
fn prop_reverse_reverse() {
    fn revrev(xs: Vec<usize>) -> bool {
        let rev: Vec<_> = xs.clone().into_iter().rev().collect();
        let revrev: Vec<_> = rev.into_iter().rev().collect();
        xs == revrev
    }
    QuickCheck::new()
        .tests(10_000)
        .quickcheck(revrev as fn(Vec<usize>) -> bool);
}
```

Using explicit configuration means you can't use the `quickcheck!` macro, but such is life.

**Comment by felix91gr** [comment]
Oh. I didn't know I could write it like that. That is awesome! Thank you, @BurntSushi <3

**Comment by felix91gr** [comment]
I will close this issue. Now I think I have everything I needed :)

**Comment by BurntSushi** [comment]
@felix91gr Great! Feel free to ask more questions if you run into problems!
