### ISSUE TITLE
Pretty print output?

### ISSUE THREAD

**Issue by alok** [BurntSushi/quickcheck#220]
I don't know if you can really control this, but would it be possible to more clearly distinguish failing inputs?

The current errors look like `thread 'tests::prop' panicked at '[quickcheck] TEST FAILED. Arguments: ([0, 1])'`, which would be easier to read with something like:

```
[quickcheck] TEST FAILED.

Arguments: ([0, 1])
```

**Comment by BurntSushi** [comment]
Not really. The "panicked at" is coming from the test harness. I think sticking with one line is probably simplest. Adding new lines will most likely just turn it more into a soup.

With that said, if someone has any better ideas here, I'd be happy to just take a PR.
