### ISSUE TITLE
Better way to implement arbitrary with floats

### ISSUE THREAD

**Issue by JoshMcguigan** [BurntSushi/quickcheck#229]
I have a custom `Arbitrary` impl for a struct which is made up of four floats. Is there a reason `Gen` doesn't expose any methods for directly creating float values? I'd be happy to implement this if you'd be willing to add this. 

```rust
    impl Arbitrary for Q {
        fn arbitrary<G: Gen>(g: &mut G) -> Self {
            Q {
                q1: g.next_u32() as f32 / core::u32::MAX as f32 * 2. - 1.,
                q2: g.next_u32() as f32 / core::u32::MAX as f32 * 2. - 1.,
                q3: g.next_u32() as f32 / core::u32::MAX as f32 * 2. - 1.,
                q4: g.next_u32() as f32 / core::u32::MAX as f32 * 2. - 1.,
            }
        }
    }
```

**Comment by BurntSushi** [comment]
Anything that implements `Gen` also implements `RngCore` and, consequently, [`Rng`](https://docs.rs/rand/0.6.5/rand/trait.Rng.html), which has a [`gen`](https://docs.rs/rand/0.6.5/rand/trait.Rng.html#method.gen) method that should do what you want.

**Comment by JoshMcguigan** [comment]
Thanks for the quick response. For future readers, in order to use `gen` I needed to add `use rand::Rng;` and add `rand` as a dependency of my crate.
