### ISSUE TITLE
New release with dependicies update?

### ISSUE THREAD

**Issue by Dushistov** [BurntSushi/quickcheck#232]
Is it possible to make new release with updated dependencies:
```
rand_core -> 0.4
env_logger -> 0.6
```
?

To make possible to use quickcheck without building two version of log, two versions of rand_core and so on.

**Comment by BurntSushi** [comment]
Done in `quickcheck 0.8.2`.

**Comment by Dushistov** [comment]
@BurntSushi  Thank you!
