### ISSUE TITLE
Document new MSRV policy

### ISSUE THREAD

**Issue by HeroicKatora** [BurntSushi/quickcheck#250]
The readme includes a section on how `0.8` requires 1.30 but does not mention the requirements or any commitment for the newest version, `0.9`. I suppose it is 1.32 due to the MSRV commitment from `rand = 0.7`.

**Comment by BurntSushi** [comment]
quickcheck has no MSRV policy other than "do what rand does" since `rand` is a public dependency. It looks like rand has settled down a bit in recent times, but in the past, it was moving quite fast. There's really no reasonable alternative.

The README does look weird though. I'll fix that.

**Comment by HeroicKatora** [comment]
It [*sounds*](https://github.com/rust-random/rand#rust-version-requirements) like it has an MSRV right now:

> Since version 0.7, Rand requires Rustc version 1.32 or greater.
