### ISSUE TITLE
Implement Arbitrary for `std::fmt::Formatter`

### ISSUE THREAD

**Issue by maxbla** [BurntSushi/quickcheck#253]
This could be helpful for users implementing formatting traits on types defined in their crate.

I'm not sure if this will be easy, as "Users do not construct Formatters directly; a mutable reference to one is passed to the fmt method of all formatting traits" ([docs](https://doc.rust-lang.org/std/fmt/struct.Formatter.html)) I would be happy to submit a PR for this, but I generally gauge support first.

**Comment by BurntSushi** [comment]
Could yoy elaborate a bit on the kinds of properties you would test with this?

Also, could you say how you see such an impl existing? If you can't construct a value then I don't think there's much you can do...

**Comment by maxbla** [comment]
You might test that `Display`ing some number type always has 10 digits after the `.` when the `precision` of `Formatter` is 10. 

Now that I'm writing it down, this doesn't make a whole lot of sense. The test would fail if `width` were large and `align` was `Alignment::Left`

**Comment by maxbla** [comment]
A more obvious property is that formatting should be deterministic i.e. for every `Formatter` and user defined type, formatting twice should give the same result.

**Comment by BurntSushi** [comment]
I'm not really sure how useful this is. And as I mentioned, given that one cannot construct a value of this type, I don't see how to fulfill this request. Feel free to re-open if you see a way to do this.
