### ISSUE TITLE
Question: Where to put Arbitrary implementations?

### ISSUE THREAD

**Issue by turion** [BurntSushi/quickcheck#256]
## Situation

* I have a crate `foo` with a struct `Foo`
* I have `quickcheck` in the `dev-dependencies`, and I want to keep it there
* I've implemented the `Arbitrary` trait and put this behind `#[cfg(test)]`
* I have another crate `bar` that uses `Foo`
* I have a test in `bar` that should quickcheck, and this test has a `Foo` as input

## Problem

The test doesn't compile because it doesn't find the `Arbitrary` implementation for `Foo`.

## Workaround

* Remove `#[cfg(test)]` from the `Arbitrary` implementation of `Foo`
* This forces me to move `quickcheck` from `dev-dependencies` to `dependencies`
* This means that `quickcheck` is available in production. I don't want that.

## Question

What's best practice? Where should I put the `Arbitrary` implementations such that they can be seen across crates in tests?

**Comment by BurntSushi** [comment]
The only way I see how to do this is to use Cargo features and make `quickcheck` an optional non-dev dependency.
