### ISSUE TITLE
When 1.0?

### ISSUE THREAD

**Issue by ordian** [BurntSushi/quickcheck#266]
Hey @BurntSushi, 480a879a00922b3dd86915d787082f9c650db33f was merged a week ago, when do you plan to make a new release? Now that rand 0.8 is released it the upgrade is pending on quickcheck release.

**Comment by BurntSushi** [comment]
I'll do it when I do it. As I said in #264, I don't consider the rand issue high priority.

Otherwise, I do this in my free time and my free time does not have a schedule.

**Comment by ordian** [comment]
Ok, thanks. I appreciate you doing this in your free time and was just curious whether it would take a day, a week or a month.
But from your reply I get the answer is more than a day.

**Comment by BurntSushi** [comment]
`quickcheck 1.0.0` is now on crates.io. cc @jhpratt @lopopolo

**Comment by jhpratt** [comment]
Thanks for the heads up!

**Comment by lopopolo** [comment]
@BurntSushi I don't know if QuickCheck has a trophy case, but the 1.0 release had some changes to the `Arbitrary` impl for `Vec<u8>` that found this bug: https://github.com/mruby/mruby/issues/5269.

**Comment by BurntSushi** [comment]
@lopopolo Wow, nice! And no, there's no trophy case. But thanks for sharing!
