### ISSUE TITLE
Arbitrary f32 and f64's should include special values

### ISSUE THREAD

**Issue by danburkert** [BurntSushi/quickcheck#27]
Currently `INFINITY`, `NEG_INFINITY`, `NAN` and possibly `-0.0` are never generated by quickcheck. These values are valid floats, and should be tested for.

**Comment by huonw** [comment]
Including [subnormals](https://en.wikipedia.org/wiki/Denormal_number) might be good too.

**Comment by bekh6ex** [comment]
Related problem: `f64` and `f32` values are always in range between -100 and 100
```rust
quickcheck! {
    fn float_range(n: f64) -> bool {
        n < 100.0 && n > -100.0
    }
}
```
This test never fails.

**Comment by bekh6ex** [comment]
Regarding Haskell's quickcheck and floats here is related discussion:
https://github.com/nick8325/quickcheck/issues/98

**Comment by xfix** [comment]
> However for Float, the NaN values are problematic since they violate the typeclass laws.

Doesn't sound like an issue for Rust, just saying, due to `PartialEq` and `Eq` being separate.
