### ISSUE TITLE
example case sort TEST FAILED

### ISSUE THREAD

**Issue by yq0810** [BurntSushi/quickcheck#288]
cargo run --package quickcheck --example sort 

thread 'main' panicked at '[quickcheck] TEST FAILED. Arguments: ([9223372036854775807, 9223372036854775807])', C:\quickcheck-master\src\tester.rs:165:28

**Comment by BurntSushi** [comment]
https://github.com/BurntSushi/quickcheck/blob/defde6fb0ce20b0c8c4e672aa9ae821f7d1f5b38/examples/sort.rs#L1-L2
