### ISSUE TITLE
QuickChecking Const Generic Code

### ISSUE THREAD

**Issue by markcatley** [BurntSushi/quickcheck#290]
Any thoughts on using QuickCheck on const generic code? I imagine it would be a little difficult given that you'd have to run some of the testing at compile time.
I.e. if you have:
```
pub struct Matrix<T, const ROWS: usize, const COLS: usize> {
    data: Vec<T>,
}

quickcheck! {
  fn qcheck_test<const ROWS: usize, const COLS: usize>(t: Matrix<i32, ROWS, COLS>) -> bool {
    ...
  }
}
```
I am guessing you'd have to generate a bunch of different versions of `qcheck_test` at compile time in the `quickcheck!` macro to make this work. I don't know if that is even possible. If you think it might work I'm happy to try to write some code.

**Comment by BurntSushi** [comment]
I don't understand the question. Please elaborate. Please include examples.

**Comment by markcatley** [comment]
Sorry about that. I'm not entirely sure how to show what I am asking. Can you see if the changes I've made to the initial comment makes sense to you? If not, close this and I guess I'll have to write some code that modifies the quickcheck macros and see if I can explain what I mean better.

**Comment by BurntSushi** [comment]
Yeah I guess I'm still not quite sure what you're asking. I don't see why const generic code can't be quickchecked just like anything else.

If you're talking about varying the const generic parameters themselves, then yeah, quickcheck can't and won't do that.

**Comment by markcatley** [comment]
Yes, I was thinking about varying the const generic parameters. Sorry that I wasn't clearer upfront - I wasn't sure about the language to use.

I don't understand why it can't be done - however, I can see why the tradeoffs might be not worth it. I might give the code a go and post a PR for my understanding. Feel free to close it without looking at it too hard if that's what you'd like to do.

Sorry for unnessisarily taking up your time and thank you for your working in the rust ecosystem.

**Comment by BurntSushi** [comment]
I'd love to see what you come up with personally. I wonder if we might still be missing each other here. The code will help clarify I think.
