### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by tmbull** [BurntSushi/quickcheck#315]
Hi, first of all, thanks for the library! I always enjoyed using quickcheck in Haskell and I've found that the macros you've provided make it relatively painless to quickly write quickcheck tests in Rust, even for relatively complex structs. 

I have noticed that there are a number of longstanding issues and PRs open without comment by the maintainer. 

@BurntSushi , I am just wondering if you are still maintaining this project? If not, would it be possible to either move the project elsewhere or assign additional maintainers so that we get some of these features/fixes merged in? 

Personally I am interested in #267

**Comment by BurntSushi** [comment]
It's not my current priority. If you need something soon, I suggest forking it. Transferring ownership or adding more maintainers is _more_ work for me than would be required for me to just maintain it myself.
