### ISSUE TITLE
Provide some way to fail the unit test if all the quickcheck tests were discarded

### ISSUE THREAD

**Issue by japaric** [BurntSushi/quickcheck#37]
Sometimes I write too many "discard conditions" (along with too many arguments), or sometimes I get those conditions wrong, and quickcheck ends up discarding _all_ the `10k` tests, and flagging the unit test as _passed_. IMO, either case is a bug, because I'm not actually testing anything, and I should fix the discard conditions.

Right now, the only way to detect this issue is to use `RUST_LOG=quickcheck` and look out for "Passed 0 Quickcheck tests" messages.

I would like to see some way to fail the unit test if too few quickcheck tests passed. Preferably, using a environment variable, say `QC_PASSED_TESTS_THRESHOLD=25 cargo test` will fail the unit test if less than 25 quickcheck tests passed, if the variable is unset, the threshold will be zero, which is the current behavior.

Thoughts @BurntSushi ?

**Comment by mulkieran** [comment]
I experienced a similar problem with these quite plausible looking tests: https://github.com/stratis-storage/stratisd/pull/217/commits/0f7838d536619861899cb8d49106b750d59c787d. The u64 argument never exceeded its rather low minimum value.
