### ISSUE TITLE
Does not compile with latest nightly (2015-02-19)

### ISSUE THREAD

**Issue by caspark** [BurntSushi/quickcheck#65]
There's more than a few compile errors resulting from using the latest nightly:

```
$ rustc --version
rustc 1.0.0-nightly (dfc5c0f1e 2015-02-18) (built 2015-02-19)
$ cargo build
   Compiling quickcheck v0.1.39 (file:///home/caspar/src/rust-quickcheck)
src/arbitrary.rs:150:29: 150:44 error: the parameter type `A` may not live long enough [E0310]
src/arbitrary.rs:150                 let chain = single_shrinker(None).chain(x.shrink().map(Some));
                                                 ^~~~~~~~~~~~~~~
src/arbitrary.rs:150:29: 150:44 help: consider adding an explicit lifetime bound `A: 'static`...
src/arbitrary.rs:150                 let chain = single_shrinker(None).chain(x.shrink().map(Some));
                                                 ^~~~~~~~~~~~~~~
src/arbitrary.rs:150:29: 150:44 note: ...so that the type `core::option::Option<A>` will meet its required lifetime bounds
src/arbitrary.rs:150                 let chain = single_shrinker(None).chain(x.shrink().map(Some));

* etc etc for another 85 lifetime-related error messages *

src/tester.rs:189:30: 189:36 error: type `core::result::Result<std::thread::JoinGuard<'_, T>, std::io::error::Error>` does not implement any method in scope named `join`
src/tester.rs:189                             .join()
                                               ^~~~~~
src/tester.rs:446:29: 446:35 error: type `core::result::Result<std::thread::JoinGuard<'_, T>, std::io::error::Error>` does not implement any method in scope named `join`
src/tester.rs:446         match t.scoped(fun).join() {
                                              ^~~~~~
error: aborting due to 88 previous errors
Could not compile `quickcheck`.
```

I had a shot at fixing it without any success (still getting my head around lifetimes and associated syntax) so I figured the next best thing is reporting it.

Related: maybe it'd be worth fixing up http://www.rust-ci.org/BurntSushi/quickcheck ? Seems like it hasn't kicked off a new build in almost a year; it's not particularly clear on that page but on the main rust-ci.org page it claims it was unable to build and needs the owner to authenticate, or something along those lines.

**Comment by BurntSushi** [comment]
> Related: maybe it'd be worth fixing up http://www.rust-ci.org/BurntSushi/quickcheck ? Seems like it hasn't kicked off a new build in almost a year; it's not particularly clear on that page but on the main rust-ci.org page it claims it was unable to build and needs the owner to authenticate, or something along those lines.

I'm using travis, not rust-ci.org. I tried using rust-ci.org a while back, but it was slow and documentation hosting didn't work. So I moved away from it and didn't look back. What advantages does it have over Travis? (Keeping in mind that I've created a process for hosting docs myself.)

**Comment by BurntSushi** [comment]
Unfortunately, the latest nightly for me is `6c065fc8c` (built on `2015-02-18`), which compiles QuickCheck. So I won't be able to fix it just yet.

I think that leaves you with two options: 1) rollback to older nightly (yuck) or 2) try your hand at fixing the errors. The lifetime errors don't look too pleasant, but e.g., you might try changing this:

```rust
impl<A: Arbitrary> Arbitrary for Option<A> {
```

to this:

```rust
impl<A: Arbitrary+'static> Arbitrary for Option<A> {
```

And my guess is that you'll have to do it for a lot of other impls too.

The other error (with `std::thread::JoinGuard`) can be fixed by replacing this code (on line `tester.rs:446`):

```rust
match t.scoped(fun).join()
```

with this code:

```rust
match t.scoped(fun).unwrap().join()
```

Unwrapping is bad form, but the [docs say](http://doc.rust-lang.org/std/thread/struct.Builder.html#errors) that an error occurs only if the OS can't create a thread. I'm OK with panic'ing in that case. (Or you can handle the error and convert it to a string, since the enclosing function `safe` returns a `Result<T, String>`. This is probably better.)

**Comment by caspark** [comment]
Maybe it was different when you tried it originally, but I was under the impression that rust-ci.org just kicks off the Travis build when there's a new rust nightly? (gleaned from the header at the top of rust-ci.org)

Strange, I'm also on 64 bit Linux and used `curl -s https://static.rust-lang.org/rustup.sh | sudo sh` to get the latest 3-4 hours ago or so, which downloaded from `https://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz`. Surely that's a consistent nightly each day? Unless you meant you haven't updated recently, in which case: nevermind!

Thanks for the pointers to fixing the compile errors; I'll have another go at it tomorrow.

**Comment by BurntSushi** [comment]
@caspark Oh, that's a neat benefit of rust-ci.org. If it was 6 months ago, I'd probably heed your advice, but we're getting to a point where breaking changes are settling down *a lot*. With beta around the corner, I'm just going to sit tight for now. :-) (I have to limit to number of things that can distract me! :P)

Weird about the nightly. I use Arch's AUR package `rust-nightly-bin` which I thought [pulled directly from the same URL](https://aur.archlinux.org/packages/ru/rust-nightly-bin/PKGBUILD). In any case, if you wait until tomorrow, I will have hopefully fixed things by then. :-)

**Comment by caspark** [comment]
Looks like you beat me to fixing all the compile errors, so I'll close this :)

**Comment by BurntSushi** [comment]
Yeah, it was quite a bit trickier than I thought. Required a bit of refactoring because of changes in the `std::thread` module. And some use of special phantom markers. Yikes!
