### ISSUE TITLE
How to make generated parameters test certain cases

### ISSUE THREAD

**Issue by febeling** [BurntSushi/quickcheck#76]
I have another question about writing QuickCheck tests.

My function under test, `edit_distance`, has another property, which I want to quickcheck.

    It is zero if and only if the strings are equal.

This requires that both parameters reasonably often are equal. I have a naive implementation here:

https://github.com/febeling/edit-distance/commit/30532c2a444328ee9dbf75eda5445e8ce9a80927#diff-475a9530a9c1e888d097445199b74c2fR75

But when I run it and prepare the code a bit, I have seen that the the condition 'strings are equal' is never met. I guess that's a common problem in quickcheck test. Is there a good way to deal with this case?

**Comment by bluss** [comment]
You can use the `-> TestResult` form of a property and return `TestResult::discard()` when strings are not equal. This will let  you spin until you've had the full count of non-discarded test results. Of course, if it's very improbable to generate strings that are equal, then it will waste a lot of cpu time before it's done. There is no adaptive logic on discard, it just doesn't count that testcase towards the number of tests (100) it does however count towards max_tests (10000), so it will return Ok if you did not find 100 non-discarded tests in 10000.

**Comment by BurntSushi** [comment]
Ah, for some reason, I missed this issue. Thanks @bluss for commenting and bringing it to my attention. :-)

The approach @bluss mentions is good, but only if you expect the condition you want to test for to happen reasonably often. In your case, that's probably not a good assumption.

Instead, I'd recommend defining your own string type and implementing arbitrary such that there is a good likelihood that two strings are equal. For example, by limiting their length and/or alphabet. You can see an example here: https://github.com/rust-lang/regex/blob/master/regex-syntax/src/properties.rs#L91-L107

**Comment by febeling** [comment]
Thank you both for answering! It makes sense.
