### ISSUE TITLE
source trait is private (Rng)

### ISSUE THREAD

**Issue by twittner** [BurntSushi/quickcheck#82]
Please consider this test case:
```rust
extern crate quickcheck;

use quickcheck::{Arbitrary, Gen};

#[derive(Clone)]
pub struct Foo(u8);

impl Arbitrary for Foo {
    fn arbitrary<G: Gen>(g: &mut G) -> Foo {
        Foo(g.gen())
    }
}
```
Compilation with `rustc 1.3.0-nightly (0c052199b 2015-07-11)` gives:
```
src/lib.rs:10:13: 10:20 error: source trait is private
src/lib.rs:10         Foo(g.gen())
                          ^~~~~~~
```

I think it is necessary to export not only `Gen` but also it's parent trait `Rng`:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index f13fcdc..ab1698b 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -10,6 +10,7 @@
 #[macro_use] extern crate log;
 extern crate rand;
 
+pub use rand::Rng;
 pub use arbitrary::{
     Arbitrary, Gen, StdGen,
     empty_shrinker, single_shrinker,
```

**Comment by apasel422** [comment]
The other solution is to add this to your crate:

```rust
extern crate rand;
use rand::Rng;
```

**Comment by BurntSushi** [comment]
What is the right thing to do here? Are there any downsides to re-exporting it? That certainly seems like the more convenient option (and one I hadn't thought of!).

**Comment by twittner** [comment]
> The other solution is to add this to your crate: [...]

Yes. In addition it requires adding `rand` explicitly as a dependency in your `Cargo.toml` file.

**Comment by Wilfred** [comment]
Related: https://github.com/rust-lang/rust/issues/22050

**Comment by BurntSushi** [comment]
OK, I fixed this by re-exporting the `rand::Rng` type. I'm not sure if it's the right solution, but it seems better than requiring an explicit dependency on `rand` just to use methods defined by the `Gen` trait.
