### ISSUE TITLE
'Rng.gen_range called with low >= high'

### ISSUE THREAD

**Issue by twittner** [BurntSushi/quickcheck#83]
This can happen due to invalid casts from `quickcheck::Gen::size` of type `usize` to various other integer types with a value range smaller than `usize` (cf. [quickcheck::arbitrary::unsigned_arbitrary](https://github.com/BurntSushi/quickcheck/blob/848acee19b180b44f7cf1d74ac431bd68efd8667/src/arbitrary.rs#L370)).

Test case:
```rust
#[test]
fn test() {
    fn prop(_: u8) -> bool { true }

    QuickCheck::new()
        .gen(StdGen::new(rand::thread_rng(), 1024))
        .quickcheck(prop as fn(u8) -> bool)
}

```

**Comment by BurntSushi** [comment]
Thanks for the report!
