### ISSUE TITLE
can you explain to me

### ISSUE THREAD

**Issue by RoboMantis** [BurntSushi/quickcheck#84]
the out_of_bounds code, what exactly does this do line by line?

```rust
extern crate quickcheck;

use quickcheck::{TestResult, quickcheck};

fn main() {
    fn prop(length: usize, index: usize) -> TestResult {
        let v: Vec<_> = (0..length).collect();
        if index < length {
            TestResult::discard()
        } else {
            TestResult::must_fail(move || {
                v[index]
            })
        }
    }
    quickcheck(prop as fn(usize, usize) -> TestResult);
}
```

**Comment by RoboMantis** [comment]
im new to rust

**Comment by BurntSushi** [comment]
This looks like a test to make sure that `TestResult::must_fail` works. In particular, the test passes *only if* all inputs either result in the test being discarded or if `v[index]` panics (as a result of the index being out of bounds).

**Comment by BurntSushi** [comment]
If you have more specific questions, I'd be happy to try and help you work through them.
