### ISSUE TITLE
Add ability to specify number of tests to the quickcheck macro

### ISSUE THREAD

**Issue by Wilfred** [BurntSushi/quickcheck#85]
I have a quickcheck test using `Vec<EnumWithManyVariants>` and my tests rarely fail. It would be nice if I could set an environment variable to make quickcheck try more possible inputs.

**Comment by RoboMantis** [comment]
could you send me the
vec<quickcheck> code? im new to rust but this sound usefull. what is it? a
debugger?

**Comment by BurntSushi** [comment]
@Wilfred To clarify, have you seen the `tests` method? http://burntsushi.net/rustdoc/quickcheck/struct.QuickCheck.html#method.tests Or are you specifically asking for this to be settable via an environment variable?

**Comment by andreasfrom** [comment]
It would be nice to be able to control this when using the `#[quickcheck]` attribute also.

**Comment by Wilfred** [comment]
I think my use case is probably the same as Andreas: I have a load of tests using the `#[quickcheck]` attribute and I can't change the number of tests run. It would probably make more sense if it could be controlled per-test, so I could increase the number for tests which I've observed to find failures occasionally.

**Comment by remexre** [comment]
I think this is already implemented: https://github.com/remexre/quickcheck/blame/master/src/tester.rs#L20

Close as fixed?

**Comment by Wilfred** [comment]
That's certainly helpful, because users can explicitly re-run a single test and set QUICKCHECK_TESTS to explore more test cases if they wish.

However, it doesn't meet the following usecases:

* If I have a test that runs slowly, I might want to lower the number of test cases attempted
* If I have a fast test and a large test case space (so my tests occasionally fail when doing TDD), I might want to increase the number of test cases attempted

In both of these cases, I want to change the number of test cases per test, and make a permanent change.

That's my usecase at least. If you think the current functionality is sufficient for quickcheck's goals, I understand.

**Comment by remexre** [comment]
It'd be "probably not too hard" to change the `quickcheck!` macro to allow a per-test `#[quickcheck_tests = 1234]` attribute as well; if you want to try that, feel free, otherwise I might play around with it if I have a free weekend.
