### ISSUE TITLE
Implement Wrapping<integer type> for Arbitrary

### ISSUE THREAD

**Issue by Wilfred** [BurntSushi/quickcheck#87]
It would be nice to be able to use quickcheck with (e.g.) `Wrapping<u8>`. I'm not sure I can fix this in my own code, adding

``` rust
impl Arbitrary for Wrapping<u8> {
    fn arbitrary<G: Gen>(g: &mut G) -> Wrapping<u8> {
        Wrapping(Arbitrary::arbitrary(g))
    }
}
```

generates a compile error because neither `Arbitrary` nor `Wrapping` were defined by me.

**Comment by BurntSushi** [comment]
Looks like an `Arbitrary` impl was added for `Wrapping`.
