### ISSUE TITLE
testable functions with more arguments

### ISSUE THREAD

**Issue by droundy** [BurntSushi/quickcheck#88]
I very quickly ran into the four-argument limit, so it'd be lovely to have Testable instances for functions with more arguments.

**Comment by BurntSushi** [comment]
The code to provide those instances is pretty hairy. I'd prefer that you just use tuples. e.g., Instead of

```rust
fn prop(x: i64, y: u64, z: i32, a: String, b: Vec<String>, c: f32) -> bool { ... }
```

use

```rust
fn prop((x, y, z): (i64, u64, i32), (a, b, c): (String, Vec<String>, f32)) -> bool { ... }
```

**Comment by droundy** [comment]
I can do that.  Perhaps you can update the README to give this advice
rather than the advice to submit an issue? It might even be nicer to remove
all the multiple-argument instances in favor of always requiring a single
Arbitrary instance.  Then the error messages might be more clear...
