### ISSUE TITLE
Edge cases

### ISSUE THREAD

**Issue by fkjogu** [BurntSushi/quickcheck#90]
Is it possible to also define edge cases beside the random data without implementing my own Arbitrary type?

Of course for such cases I could just use normal testing…

**Comment by BurntSushi** [comment]
The answer to all questions starting with: "How do I customize the data generated for testing properties?" is "Define your own type and impl the `Arbitrary` type."

**Comment by BurntSushi** [comment]
One form of relief here is the ability to export failing test cases and provide some way to re-run them. This is #40.
