### ISSUE TITLE
Debug trait somehow getting lost (?) making debugging difficult

### ISSUE THREAD

**Issue by kazagistar** [BurntSushi/quickcheck#91]
## Expected

Details about why my my data structure failed.

## Actual

> UNABLE TO SHOW RESULT OF PANIC.

## Details

(I am still learning Rust, so bear with me if my code is dumb or I miss something obvious.)

I am trying to define simple, stable-compatible quickcheck tests for a trait, that can be reused to test different data structures that implement it. In this case, I am trying to test a persistent heap.

[Data structure + generic test.](https://github.com/kazagistar/okasakish/blob/21a43f45d9cbc3633fef7510b8b21a607bdaf2f6/src/heap.rs)

Unfortunately, one of my two implementations is broken somewhere, but the only information I get out of quickcheck is `Error: "UNABLE TO SHOW RESULT OF PANIC."', <path>/quickcheck-0.2.21/src/tester.rs:113`.

[Link to broken build.](https://travis-ci.org/kazagistar/okasakish/jobs/76832591)

[Link to broken usage location](https://github.com/kazagistar/okasakish/blob/21a43f45d9cbc3633fef7510b8b21a607bdaf2f6/src/binomial_heap.rs#L145)

The data structure in question has `#[derive(Debug)]` and I have tested that `println("{:?}", s)` works for this instance of the data structure, so I don't know why I am not getting any other information about the panic, and I don't know what to do to make the situation better.

**Comment by BurntSushi** [comment]
That error happens when the value that is *panicked* doesn't implement the `Debug` trait. I'm not sure what exactly is causing the panic, but you have a few options:

1. QuickCheck is actually giving you more information. In particular, it's telling your the arguments used that caused the failure (this is the "witness"): `Arguments: ([0])`.
2. You may have more luck by setting the environment variable `RUST_BACKTRACE=1` when running `cargo test`. The key will be to look for the backtraces produced as part of the panic while tests are running. Right now, they appear as this in your build output: `thread 'safe' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:362`.

**Comment by kazagistar** [comment]
I ended up finding the bug with the backtrace option (thanks!), but I am still unsure why Quickcheck was not able to print the value. The value that panicked was an `Option<i32>`... however, in the context, it was generic (A value of `Option<T> where T: Ord + Clone + Debug + Arbitrary`). Either way, thanks for the help.

**Comment by BurntSushi** [comment]
Strange. This is the relevant code: https://github.com/BurntSushi/quickcheck/blob/master/src/tester.rs#L409-L419

I'll leave this open. Ideally, we could get a smaller test case that is easier to debug.

**Comment by bluss** [comment]
`match any_err.downcast_ref::<&Debug>() ` is very “optimistic”. Downcasting an Any is only possible to the exact type that was packaged up into the `Any`.

**Comment by BurntSushi** [comment]
Right, it basically never works. Are we SOL here? Or is there some other way to show the panic? If most panics are strings, then maybe we should try `&str` and `String` too.

**Comment by huonw** [comment]
I think it's basically impossible to literally satisfy `&Debug` (that would require panicking with a `&'static Debug` trait object), so it just make sense to try `&str` and `String`, which should cover typical panics from the `assert*` macros. I guess it doesn't cost much to also check fancier things like `Box<Debug>` but they seem very unlikely to be triggered.

**Comment by yggie** [comment]
Any updates on this issue? I am running into lots of `"UNABLE TO SHOW RESULT OF PANIC."` messages and it is hiding the cause of the panics in my code.

**Comment by bluss** [comment]
Sure, I have posted a PR to fix. Depends on the resolution of shrinking prs first though.

**Comment by bluss** [comment]
@yggie Do you have interesting nonstandard panics? My fix only handles &str and String cases, which should be all assertions and all panics that use strings as the message.

**Comment by yggie** [comment]
@bluss I don’t do anything special with panics, I send `&str` most of the time, so that would solve my problem!
