### ISSUE TITLE
RUST_LOG has no effect

### ISSUE THREAD

**Issue by tari** [BurntSushi/quickcheck#95]
README.md:

> N.B. When using quickcheck (either directly or via the attributes), RUST_LOG=quickcheck enables info! so that it shows useful output (like the number of tests passed). This is not needed to show witnesses for failures.

`RUST_LOG` no longer controls the output of the `log` crate itself. The old behavior can be replicated with [`env_logger`](https://crates.io/crates/env_logger), or the logging behavior can be changed (and the documentation be updated).

**Comment by BurntSushi** [comment]
Yeah, this used to work way back when before the logging stuff was rearranged. I didn't really keep up with it.

I guess I'd recommend either removing the feature or figuring out how to use `env_logger`.
