### ISSUE TITLE
quickcheck depends on WinAPI?

### ISSUE THREAD

**Issue by vi** [BurntSushi/quickcheck#97]
```
 Downloading rand v0.3.11 (reasonable - quickcheck is a randomized test)
 Downloading log v0.3.2 (reasonable - it's omnipresent)
 Downloading winapi v0.2.4 ( ??? )
 Downloading quickcheck v0.2.24
```

**Comment by BurntSushi** [comment]
Please look at the Cargo.toml for the direct dependencies: https://github.com/BurntSushi/quickcheck/blob/master/Cargo.toml#L16-L19 **There is no `winapi`.

Therefore, `winapi` must be a dependency of one of quickcheck's dependencies.

In this case, it is a dependency of [`rand`](https://crates.io/crates/rand).

**Comment by tomjakubowski** [comment]
winapi is an empty crate on all non-Windows platforms. The maintainers of some crates (rand, in this case) prefer to just unconditionally depend on it than to get into platform-specific dependencies. See this for more details. https://github.com/rust-lang-nursery/rand/pull/65
